### ISSUE TITLE
Link to the CLI

### ISSUE THREAD

**Issue by tomek-he-him** [andrewrk/node-mv#18]
Hi,

some time ago we had a short discussion in #12. I found the time to implement this today: https://github.com/studio-b12/mve.

How about adding a link somewhere?

**Comment by andrewrk** [comment]
I'll do that if for some reason I personally start using this project instead of the normal mv utility and want to promote it. Until then, you'll have to be satisfied with being linked to here: https://www.npmjs.com/browse/depended/mv

Nothing against you; I just want to protect my reputation by only endorsing code that I can personally vouch for, and I don't have the motivation to do that for your project. I'm busy working on [other](https://github.com/andrewrk/genesis) [stuff](https://github.com/andrewrk/libsoundio).

**Comment by tomek-he-him** [comment]
>  if for some reason I personally start using this project instead of the normal mv utility

I only really use it in npm scripts. They should be platform-independent.

> I just want to protect my reputation by only endorsing code that I can personally vouch for

I do my best to write quality code. But fair enough, I see your point there.

**Comment by andrewrk** [comment]
> I only really use it in npm scripts. They should be platform-independent.

That makes sense.
